name: new-pull-request

on:
  release:
    types:
      - published

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Git config
      run: |
        git config --local user.email "oinume@gmail.com"
        git config --local user.name "actions"
    - name: Create local changes
      run: |
        echo $GITHUB_REF | sed 's/refs\/tags\///' > VERSION.txt
        cat VERSION.txt
        perl -v
    - name: Commit files
      run: |
        git commit -m "Update VERSION" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
