name: use-local-action
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show branch name
        run: |
          BRANCH=$(basename ${{ github.ref }})
          echo $BRANCH
