name: sync-master-into-db-migration

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Git config
        run: |
          git config --local user.email "oinume@gmail.com"
          git config --local user.name "oinume"
      - name: Git merge
        run: |
          git pull origin db-migration
#          git branch -a
#          git checkout db-migration
#          git branch -a
#          git merge master
#      - name: Push to db-migration branch
#        uses: ad-m/github-push-action@v0.5.0
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          branch: db-migration
