name: use-local-action

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Call hello world action
        uses: ./.github/actions/hello-world-action